# Generated by Django 5.0.3 on 2024-03-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_userd_id_task_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Titulo'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('user_id', 'title')},
        ),
    ]
